name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t sbehdad/score-predictor:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag sbehdad/score-predictor:latest sbehdad/score-predictor:latest
          docker push sbehdad/score-predictor:latest

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Git credentials helper
        run: |
          git config --global credential.helper 'cache --timeout=3600'
          echo "https://${{ secrets.GH_PAT }}:@github.com" > ~/.git-credentials

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync changes to GitHub and Hugging Face" || echo "No changes to commit"
          git push https://github-actions[bot]:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} main
        shell: bash

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://${{ secrets.HF_USERNAME }}:$HF_TOKEN@huggingface.co/spaces/sbehdadk/score-predictor main
