name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t sbehdad/score-predictor:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag sbehdad/score-predictor:latest sbehdad/score-predictor:latest
          docker push sbehdad/score-predictor:latest

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync changes to GitHub and Hugging Face" || echo "No changes to commit"
          git config lfs.https://github.com/${{ github.repository }}.locksverify false
          git push https://github-actions[bot]:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        shell: bash

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://sbehdadk:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/sbehdadk/score-predictor main
