name: Sync to GitHub and Hugging Face

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  deployments: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Disable LFS Locking
        run: git config lfs.https://github.com/your-username/your-repo.git/info/lfs.locksverify false

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync changes to GitHub and Hugging Face" || echo "No changes to commit"

      - name: Push to GitHub
        run: git push origin main

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://huggingface.co/spaces/sbehdadk/score-predictor.git
          git push https://sbehdadk:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/sbehdadk/score-predictor.git main
